/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#0055A5',
        secondary: '#EFF1F2',
        'light-blue': '#0093D0',
        'spk-dark': '#222222',
        'spk-muted': '#5B727C',
        'border-grey': '#D6DEE1',
        'bg-grey-light': '#F8F8F8',
        'muted-blue': '#93D6F2',
        'spk-yellow': '#FCB034',
        placeholder: '#A4B5BC',
        error: '#F54747',
        'pale-blue': '#CAE9F6',
        'icons-blue': '#C2EBFC',
        'success-green': '#2AC16B',
        'pale-green': '#CFEEDB',
        'pale-pink': '#F5D3DF',
        'orange-custom': '#FFDAC3',
        'ctp-heading': '#3C3C3C',
        'ctp-table-row': 'F7F8F8',
      },
      fontSize: {
        small: '1.2rem',
        regular: '1.4rem',
        body: '1.6rem',
        medium: '1.8rem',
        'body-featured': '2rem',
        21: '2.1rem',
        cart: '2.2rem',
        h2: '2.4rem',
        leading: '2.5rem',
        'h1-mobile': '2.6rem',
        qr: '2.8rem',
        30: '3rem',
        40: '4rem',
        h1: '4.8rem',
      },
      lineHeight: {
        15: '1.5rem',
        10: '1rem',
        14: '1.4rem',
        16: '1.6rem',
        18: '1.8rem',
        20: '2rem',
        24: '2.4rem',
        30: '3rem',
        32: '3.2rem',
        34: '3.4rem',
        40: '4rem',
        58: '5.8rem',
      },
      fontFamily: {
        'noto-sans': 'Noto Sans',
        roboto: 'Roboto',
      },
      padding: {
        book: '0.3rem',
        menu: '1.7rem',
        qr: '2.2rem',
        news: '3.5rem',
        footer: '3.8rem',
        'footer-mobile': '17.5rem',
        'mobile-nav': '4.5rem',
        'car-park': '5.5rem',
        h1: '7rem',
        'section-top': '9rem',
        'component-bottom': '11rem',
      },
      margin: {
        qr: '3.5rem',
      },
      opacity: {
        10: '0.1',
        20: '0.2',
        30: '0.3',
        40: '0.4',
        70: '0.7',
      },
      zIndex: {
        60: 60,
        70: 70,
      },
      borderColor: {
        'online-selected': '#0093D0',
        'offline-selected': '#0055A5',
      },
      inset: {
        'booking-wrapper': '7.2rem',
      },
    },
  },
  plugins: [],
}
